version: '3.8'

services:
  discord-bot:
    build: .
    container_name: dc_partybot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - COMMAND_PREFIX=${COMMAND_PREFIX:-!}
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    volumes:
      # 掛載數據目錄以保持持久性
      - ./data:/app/data
      # 掛載日誌目錄
      - ./logs:/app/logs
      # 掛載 cookies 檔案
      - ./youtube.cookies:/app/youtube.cookies
    networks:
      - bot-network
    # 資源限制
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # 健康檢查
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; requests.get(\"https://discord.com/api/v10/gateway\", timeout=5)'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge

# 可選：持久化卷
# volumes:
#   redis_data: