version: '3.8'

services:
  discord-bot:
    build: .
    container_name: dc_partybot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - COMMAND_PREFIX=${COMMAND_PREFIX:-!}
      - PYTHONUNBUFFERED=1
      - PYTHONHTTPSVERIFY=0
      - YT_DLP_SSL_NO_VERIFY=1
      - TZ=Asia/Taipei
      # 音訊相關設定
      - FFMPEG_LOGLEVEL=warning
      - DISCORD_VOICE_RECV_THREADS=2
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      # 掛載 cookies 文件（如果存在）
      - ./youtube.cookies:/app/youtube.cookies:ro
    networks:
      - bot-network
    # 資源限制
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 384M
          cpus: '0.5'
    # 健康檢查
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; import os; sys.exit(0 if os.path.exists('/app/main.py') else 1)"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 20s
    # 日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    # 安全設定
    security_opt:
      - no-new-privileges:true
    # 確保容器不會以 root 運行（可選）
    # user: "1000:1000"

networks:
  bot-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500