[phases.setup]
nixPkgs = [
    "ffmpeg",
    "libopus",
    "python311",
    "python311Packages.pip"
]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python3 -m ensurepip",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
