[phases.setup]
providers = ["python"]
aptPkgs = [
  "...",
  "python3-pip",
  "libopus0",
  "opus-tools",
  "libopusfile0"
]
nixPkgs = [
  "...",
  "python3",
  "python3Packages.virtualenv",
  "curl",
  "ffmpeg-full",
  "opus",
  "opusfile",
  "libopus"
]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "source /app/venv/bin/activate && python3 -m pip install --upgrade pip",
  "source /app/venv/bin/activate && python3 -m pip install -r requirements.txt",
  "source /app/venv/bin/activate && python3 -m pip install PyNaCl",
  "which ffmpeg > /dev/null || ln -s /usr/bin/ffmpeg /usr/local/bin/ffmpeg"
]

[start]
cmd = "source /app/venv/bin/activate && python main.py"
