[phases.setup]
providers = ["python"]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "python39Packages.setuptools",
    "ffmpeg"
]

aptPkgs = [
    "opus-tools"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
