[phases.setup]
providers = ["python"]
aptPkgs = [
  "python3-pip",
  "libopus0",
  "opus-tools",
  "libopusfile0"
]

nixPkgs = [
  "python3",
  "python3Packages.virtualenv",
  "ffmpeg-full"
]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "source /app/venv/bin/activate && python3 -m pip install --upgrade pip",
  "source /app/venv/bin/activate && python3 -m pip install -r requirements.txt",
  "source /app/venv/bin/activate && python3 -m pip install PyNaCl"
]

[start]
cmd = "source /app/venv/bin/activate && python main.py"
