[phases.setup]
providers = ["python"]
nixPkgs = [
  "...",
  "ffmpeg",
  "opus"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
