[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev",
    "opus-tools",
    "python3",
    "python3-pip",
    "python3-venv"
]

[phases.install]
cmds = [
    "python3 -m venv /app/venv",
    ". /app/venv/bin/activate",
    "pip3 install --upgrade pip",
    "pip3 install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/python bot.py"
