[phases.setup]
providers = ["python"]
nixPkgs = [
  "...",
  "ffmpeg",
  "python3",
  "curl"
]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py | python3",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
