[phases.setup]
nixPkgs = ["ffmpeg", "python311", "python311Packages.pip"]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev",
    "python3-dev",
    "build-essential",
    "opus-tools"
]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python3 main.py"
