[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = [
    "python3",
    "python3-pip",
    "git",
    "libffi-dev",
    "libssl-dev",
    "python3-dev",
    "build-essential"
]

[phases.install]
cmds = [
    "/usr/bin/python3 -m pip install --upgrade pip",
    "/usr/bin/python3 -m pip install -r requirements.txt"
]

[start]
cmd = "/usr/bin/python3 main.py"
