[phases.setup]
nixPkgs = ["...", "ffmpeg", "python311", "python311Packages.pip"]
aptPkgs = ["...", "git", "libffi-dev", "libssl-dev"]

[phases.install]
cmds = [
    "pip3 install --upgrade pip",
    "pip3 install -r requirements.txt"
]

[start]
cmd = "python3 main.py"
