[phases.setup]
nixPkgs = [
    "ffmpeg",
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "python311Packages.virtualenv"
]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev",
    "opus-tools"
]

[phases.install]
cmds = [
    "python -m venv /app/venv",
    "source /app/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/python main.py"
