[phases.setup]
nixPkgs = ['...', 'ffmpeg', 'python311', 'python311Packages.pip']
aptPkgs = ['...', 'git', 'libffi-dev', 'libssl-dev']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'python main.py'
