[phases.setup]
nixPkgs = [
    "ffmpeg",
    "opus",
    "python3",
    "gcc",
    "pkg-config"
]

[phases.install]
cmds = [
    "which ffmpeg || true",
    "ffmpeg -version || true"
]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]
