[phases.setup]
nixPkgs = [
    "ffmpeg",
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel"
]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev",
    "opus-tools"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
