[phases.setup]
nixPkgs = [
    "ffmpeg",
    "libopus",
    "python3Full",
    "gcc",
    "pkg-config"
]

[phases.install]
cmds = [
    "which ffmpeg || true",
    "ffmpeg -version || true"
]

[phases.build]
cmds = [
    "python3 -m ensurepip",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]
