[phases.setup]
providers = ["...", "python"]
nixPkgs = ["...", "ffmpeg", "opus-tools"]
nixLibs = ["...", "gcc-unwrapped"]

[phases.install]
cmds = ["...", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 main.py"
