[phases.setup]
providers = ["...", "python"]
nixPkgs = ["...", "ffmpeg"]
nixLibs = ["...", "gcc-unwrapped"]
aptPkgs = ["...", "opus-tools"]

[phases.install]
cmds = ["...", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 main.py"
