[phases.setup]
nixPkgs = [
    "ffmpeg",
    "python311Full"
]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev",
    "opus-tools"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python bot.py"
