[phases.setup]
nixPkgs = [
    "ffmpeg",
    "python311",
    "python311Packages.pip",
    "python311Packages.wheel",
    "python311Packages.cffi",
    "python311Packages.pynacl"
]
aptPkgs = [
    "git",
    "libffi-dev",
    "libssl-dev",
    "python3-dev",
    "build-essential"
]

[phases.install]
cmds = [
    "python -m pip install --break-system-packages --upgrade pip",
    "python -m pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "python main.py"
