[phases.setup]
providers = ["python"]
nixPkgs = [
  "...",
  "ffmpeg",
  "python3",
  "python3Packages.pip",
  "python3Packages.virtualenv",
  "curl"
]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "source /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source /app/venv/bin/activate && python main.py"
