[tool.poetry]
name = "discord-party-bot"
version = "0.1.0"
description = "A Discord bot for party management"

[tool.poetry.dependencies]
python = "^3.10"
discord-py = "^2.3.2"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
