[build]
builder = "nixpacks"

[nixpacks]
setup = [
    "apt-get update",
    "apt-get install -y ffmpeg opus-tools",
    "python -m pip install --upgrade pip"
]

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
