[build]
builder = "nixpacks"

[phases.setup]
aptPkgs = [
    "ffmpeg",
    "opus-tools",
    "python3-dev",
    "build-essential"
]

[phases.install]
cmds = [
    "which ffmpeg",
    "ffmpeg -version"
]

[deploy]
startCommand = "python3 main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10