[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
    "ffmpeg",
    "opus"
]
aptPkgs = [
    "ffmpeg",
    "opus-tools",
    "python3-dev"
]

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
