[build]
builder = "nixpacks"

[nixpacks]
setup = [
    "apt-get update",
    "apt-get install -y ffmpeg opus-tools libffi-dev libnacl-dev python3-dev",
    "python -m pip install --upgrade pip"
]

[phases.setup]
nixPkgs = [
    "ffmpeg",
    "opus"
]
aptPkgs = [
    "ffmpeg",
    "opus-tools",
    "python3-dev"
]

[phases.build]
cmds = [
    "which ffmpeg",
    "ffmpeg -version"
]

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
