[build]
builder = "nixpacks"

[nixpacks]
setup = ["apt-get update", "apt-get install -y ffmpeg"]

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
